"""학교 전체 공지 테이블에 is_important 칼럼 추가

Revision ID: 0615bb4f0870
Revises: a82f47b20851
Create Date: 2025-03-13 11:54:40.974876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0615bb4f0870'
down_revision: Union[str, None] = 'a82f47b20851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notice_content_chunks_is_important', table_name='notice_content_chunks')
    op.drop_column('notice_content_chunks', 'is_important')
    op.add_column('pnu_notices', sa.Column('is_important', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_pnu_notices_is_important'), 'pnu_notices', ['is_important'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pnu_notices_is_important'), table_name='pnu_notices')
    op.drop_column('pnu_notices', 'is_important')
    op.add_column('notice_content_chunks', sa.Column('is_important', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_notice_content_chunks_is_important', 'notice_content_chunks', ['is_important'], unique=False)
    # ### end Alembic commands ###
