"""공지 및 학지시 테이블에 첨부파일 청크 추가

Revision ID: 2dd53b57821a
Revises: 9eb6940b8b77
Create Date: 2025-02-24 11:18:13.183737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd53b57821a'
down_revision: Union[str, None] = '9eb6940b8b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notice_attachments', 'notice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('notice_content_chunks', sa.Column('attachment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notice_content_chunks', 'notice_attachments', ['attachment_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_professor_detail_chunks_professor_id'), 'professor_detail_chunks', ['professor_id'], unique=False)
    op.create_index(op.f('ix_professors_department_id'), 'professors', ['department_id'], unique=False)
    op.alter_column('support_attachments', 'support_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('support_content_chunks', sa.Column('attachment_id', sa.Integer(), nullable=True))
    op.alter_column('support_content_chunks', 'support_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_support_content_chunks_support_id'), 'support_content_chunks', ['support_id'], unique=False)
    op.create_foreign_key(None, 'support_content_chunks', 'support_attachments', ['attachment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'support_content_chunks', type_='foreignkey')
    op.drop_index(op.f('ix_support_content_chunks_support_id'), table_name='support_content_chunks')
    op.alter_column('support_content_chunks', 'support_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('support_content_chunks', 'attachment_id')
    op.alter_column('support_attachments', 'support_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_professors_department_id'), table_name='professors')
    op.drop_index(op.f('ix_professor_detail_chunks_professor_id'), table_name='professor_detail_chunks')
    op.drop_constraint(None, 'notice_content_chunks', type_='foreignkey')
    op.drop_column('notice_content_chunks', 'attachment_id')
    op.alter_column('notice_attachments', 'notice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
