"""공지사항 테이블 unique key 업데이트

Revision ID: a34870887255
Revises: bf8ec2a44e18
Create Date: 2025-03-14 21:16:39.128607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34870887255'
down_revision: Union[str, None] = 'bf8ec2a44e18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notices', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('notices_category_url_key', 'notices', type_='unique')
    op.create_unique_constraint(None, 'notices', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notices', type_='unique')
    op.create_unique_constraint('notices_category_url_key', 'notices', ['category', 'url'])
    op.alter_column('notices', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
