"""공지사항 테이블에 is_important 칼럼 추가

Revision ID: a82f47b20851
Revises: abdd5590ba66
Create Date: 2025-03-12 02:32:38.360659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82f47b20851'
down_revision: Union[str, None] = 'abdd5590ba66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice_content_chunks', sa.Column('is_important', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_notice_content_chunks_is_important'), 'notice_content_chunks', ['is_important'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notice_content_chunks_is_important'), table_name='notice_content_chunks')
    op.drop_column('notice_content_chunks', 'is_important')
    # ### end Alembic commands ###
