"""공지사항 테이블에 is_important 칼럼 추가

Revision ID: abdd5590ba66
Revises: 823d5a534e83
Create Date: 2025-03-11 00:25:11.646172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abdd5590ba66'
down_revision: Union[str, None] = '823d5a534e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('is_important', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_notices_is_important'), 'notices', ['is_important'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notices_is_important'), table_name='notices')
    op.drop_column('notices', 'is_important')
    # ### end Alembic commands ###
