"""공지사항 테이블 unique key 업데이트

Revision ID: bf8ec2a44e18
Revises: 0615bb4f0870
Create Date: 2025-03-14 21:01:46.000416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf8ec2a44e18'
down_revision: Union[str, None] = '0615bb4f0870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notices_url_key', 'notices', type_='unique')
    op.create_unique_constraint(None, 'notices', ['category', 'url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notices', type_='unique')
    op.create_unique_constraint('notices_url_key', 'notices', ['url'])
    # ### end Alembic commands ###
