"""공지 테이블 인덱스 추가

Revision ID: e569f308f138
Revises: 2dd53b57821a
Create Date: 2025-02-25 16:30:51.800212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e569f308f138'
down_revision: Union[str, None] = '2dd53b57821a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notice_content_chunks_attachment_id'), 'notice_content_chunks', ['attachment_id'], unique=False)
    op.create_index(op.f('ix_support_content_chunks_attachment_id'), 'support_content_chunks', ['attachment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_content_chunks_attachment_id'), table_name='support_content_chunks')
    op.drop_index(op.f('ix_notice_content_chunks_attachment_id'), table_name='notice_content_chunks')
    # ### end Alembic commands ###
